### ISSUE TITLE
와인 찜하기 기능

### ISSUE THREAD

**Issue by youjinlee-code** [codestates/whywine-server#18]
### ISSUE
- Group:  server
- Type: feature
- Detail: 사용자가 찜하기 버튼을 누르면 해당 와인 데이터를 유저 정보에 저장한다.

### TODO
1. [x] 사용자가 찜한 와인데이터를 찾아 유저 정보에 넣어준다.
2. [x] 이미 찜한 경우에는 찜 취소하기 기능으로 가도록 반려
3. [ ] 찜이 일정 갯수 이상이면 인기 태그 추가

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
