### ISSUE TITLE
결제 시스템 step 2

### ISSUE THREAD

**Issue by json-choi** [codestates/whywine-server#27]
### ISSUE
- Group:  server,
- Type: feature
- Detail: 회원 구매 비회원구매 테스트 구매

### TODO
1. [ ] Job1 회원 구매
2. [ ] Job2 비회원 구매
3. [ ] Job3 테스트 구매

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
