### ISSUE TITLE
댓글 기능 - 댓글에 대한 좋아요, 싫어요 버튼

### ISSUE THREAD

**Issue by youjinlee-code** [codestates/whywine-server#28]
### ISSUE
- Group:  server
- Type: feature
- Detail: 댓글에 대한 좋아요, 싫어요 버튼 처리

### TODO
1. [x] 좋아요 버튼 누르면 good 테이블과 comment 테이블 업데이트
2. [x] 싫어요 버튼 누르면 bad 테이블과 comment 테이블 업데이트
3. [x] 좋아요, 싫어요를 한 번 더 눌러 취소한 경우 업데이트

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
