### ISSUE TITLE
[Server] ''hello world' 셋팅

### ISSUE THREAD

**Issue by json-choi** [codestates/whywine-server#4]
### ISSUE
- Group:  server
- Type: feature, 
- Detail: 기본 서버 구축

### TODO
1. [ ] Job1 express 서버 구축
2. [ ] Job2 mongoose 데이터베이스 모듈 설치
3. [ ] Job3 aws 배포

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
