### ISSUE TITLE
회원가입

### ISSUE THREAD

**Issue by json-choi** [codestates/whywine-server#9]
### ISSUE
- Group:  server
- Type: feature
- Detail: 암호화 된 데이터베이스로 회원가입

### TODO
1. [ ] Job1 암호화 모듈 선택
2. [ ] Job2 암호화 기능플로우 탐구
3. [ ] Job3 사용가능 체킹

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
