### ISSUE TITLE
와인 별점 메기기 기능

### ISSUE THREAD

**Issue by youjinlee-code** [codestates/whywine-server#98]
### ISSUE
- Group:  server
- Type: feature
- Detail: 각 와인에 별점을 메기는 기능

### TODO
1. [x] 와인 entity, 유저 entity에 별점 추가
2. [x] 별점 메기기 관련 API 문서작성
3. [x] 별점 메기기 기능 구현

### LABEL
`E: 1h`
`bare minimum, advanced, nightmare`
`completed`,
`bugfix`,
`dev-log`,
`KPT`,
`error handling`
